version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '4000:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - qa-network

  backend:
    build:
      context: ../QA-API
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
    networks:
      - qa-network

networks:
  qa-network:
    driver: bridge

volumes:
  mongo-data:
